### PR TITLE
Webrtc signaling fixes

### PR DESCRIPTION
**Pull request by stv0g**

### CODE REVIEW

**Comment by PJungkamp** [comment]
Since the conceal value in sul is higher than the length of the back off table, lws will should try to reconnect indefinitely. Should we make the reconnection attempts exhausted message a hard exception?

**Comment by stv0g** [comment]
I would keep this behaviour for now. WhatsApp the maximum interval between consecutive Retriever I the current Code?

**Comment by PJungkamp** [comment]
https://github.com/VILLASframework/node/blob/master/include/villas/nodes/webrtc/signaling_client.hpp#L45

`2<<16` milliseconds, so about a minute.

**Comment by stv0g** [comment]
Okay that's acceptable

**Pull request merged**
